import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.className}>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className="relative">
        <div className="max-w-7xl m-auto">{children}</div>
      </body>
    </html>
  );
}
