import { FilterObj } from "@/lib/types";

export const filterObj: FilterObj = {
  name: {
    label: "Name",
    type: "text",
    placeholder: "Enter your name",
  },
  email: {
    label: "Email",
    type: "email",
    placeholder: "Enter your email",
  },
  platforms: {
    label: "Platforms",
    placeholder: "Select platforms",
    options: [
      { value: "facebook", label: "Facebook" },
      { value: "instagram", label: "Instagram" },
      { value: "twitter", label: "Twitter" },
    ],
  },
  industry: {
    label: "Industry",
    placeholder: "Select Inudstry",
    options: [
      { value: "technology", label: "Technology" },
      { value: "finance", label: "Finance" },
      { value: "healthcare", label: "Healthcare" },
    ],
  },
  country: {
    label: "Country",
    placeholder: "Select your country",
    options: [
      { value: "AF", label: "Afghanistan" },
      { value: "AL", label: "Albania" },
      { value: "DZ", label: "Algeria" },
      { value: "AD", label: "Andorra" },
      { value: "AO", label: "Angola" },
      { value: "AR", label: "Argentina" },
      { value: "AM", label: "Armenia" },
      { value: "AU", label: "Australia" },
      { value: "AT", label: "Austria" },
      { value: "AZ", label: "Azerbaijan" },
      { value: "BS", label: "Bahamas" },
      { value: "BH", label: "Bahrain" },
      { value: "BD", label: "Bangladesh" },
      { value: "BB", label: "Barbados" },
      { value: "BY", label: "Belarus" },
      { value: "BE", label: "Belgium" },
      { value: "BZ", label: "Belize" },
      { value: "BJ", label: "Benin" },
      { value: "BT", label: "Bhutan" },
      { value: "BO", label: "Bolivia" },
      { value: "BA", label: "Bosnia and Herzegovina" },
      { value: "BW", label: "Botswana" },
      { value: "BR", label: "Brazil" },
      { value: "BN", label: "Brunei Darussalam" },
      { value: "BG", label: "Bulgaria" },
      { value: "BF", label: "Burkina Faso" },
      { value: "BI", label: "Burundi" },
      { value: "KH", label: "Cambodia" },
      { value: "CM", label: "Cameroon" },
      { value: "CA", label: "Canada" },
      { value: "CV", label: "Cape Verde" },
      { value: "CF", label: "Central African Republic" },
      { value: "TD", label: "Chad" },
      { value: "CL", label: "Chile" },
      { value: "CN", label: "China" },
      { value: "CO", label: "Colombia" },
      { value: "KM", label: "Comoros" },
      { value: "CG", label: "Congo" },
      { value: "CR", label: "Costa Rica" },
      { value: "HR", label: "Croatia" },
      { value: "CU", label: "Cuba" },
      { value: "CY", label: "Cyprus" },
      { value: "CZ", label: "Czech Republic" },
      { value: "DK", label: "Denmark" },
      { value: "DJ", label: "Djibouti" },
      { value: "DM", label: "Dominica" },
      { value: "DO", label: "Dominican Republic" },
      { value: "EC", label: "Ecuador" },
      { value: "EG", label: "Egypt" },
      { value: "SV", label: "El Salvador" },
      { value: "GQ", label: "Equatorial Guinea" },
      { value: "ER", label: "Eritrea" },
      { value: "EE", label: "Estonia" },
      { value: "ET", label: "Ethiopia" },
      { value: "FJ", label: "Fiji" },
      { value: "FI", label: "Finland" },
      { value: "FR", label: "France" },
      { value: "GA", label: "Gabon" },
      { value: "GM", label: "Gambia" },
      { value: "GE", label: "Georgia" },
      { value: "DE", label: "Germany" },
      { value: "GH", label: "Ghana" },
      { value: "GR", label: "Greece" },
      { value: "GT", label: "Guatemala" },
      { value: "GN", label: "Guinea" },
      { value: "GY", label: "Guyana" },
      { value: "HT", label: "Haiti" },
      { value: "HN", label: "Honduras" },
      { value: "HU", label: "Hungary" },
      { value: "IS", label: "Iceland" },
      { value: "IN", label: "India" },
      { value: "ID", label: "Indonesia" },
      { value: "IR", label: "Iran" },
      { value: "IQ", label: "Iraq" },
      { value: "IE", label: "Ireland" },
      { value: "IL", label: "Israel" },
      { value: "IT", label: "Italy" },
      { value: "JM", label: "Jamaica" },
      { value: "JP", label: "Japan" },
      { value: "JO", label: "Jordan" },
      { value: "KZ", label: "Kazakhstan" },
      { value: "KE", label: "Kenya" },
      { value: "KR", label: "Korea" },
      { value: "KW", label: "Kuwait" },
      { value: "KG", label: "Kyrgyzstan" },
      { value: "LA", label: "Lao People's Democratic Republic" },
      { value: "LV", label: "Latvia" },
      { value: "LB", label: "Lebanon" },
      { value: "LS", label: "Lesotho" },
      { value: "LR", label: "Liberia" },
      { value: "LY", label: "Libya" },
      { value: "LT", label: "Lithuania" },
      { value: "LU", label: "Luxembourg" },
      { value: "MG", label: "Madagascar" },
      { value: "MW", label: "Malawi" },
      { value: "MY", label: "Malaysia" },
      { value: "MV", label: "Maldives" },
      { value: "ML", label: "Mali" },
      { value: "MT", label: "Malta" },
      { value: "MX", label: "Mexico" },
      { value: "MD", label: "Moldova" },
      { value: "MC", label: "Monaco" },
      { value: "MN", label: "Mongolia" },
      { value: "MA", label: "Morocco" },
      { value: "MZ", label: "Mozambique" },
      { value: "MM", label: "Myanmar" },
      { value: "NA", label: "Namibia" },
      { value: "NP", label: "Nepal" },
      { value: "NL", label: "Netherlands" },
      { value: "NZ", label: "New Zealand" },
      { value: "NG", label: "Nigeria" },
      { value: "NO", label: "Norway" },
      { value: "OM", label: "Oman" },
      { value: "PK", label: "Pakistan" },
      { value: "PS", label: "Palestine" },
      { value: "PA", label: "Panama" },
      { value: "PG", label: "Papua New Guinea" },
      { value: "PY", label: "Paraguay" },
      { value: "PE", label: "Peru" },
      { value: "PH", label: "Philippines" },
      { value: "PL", label: "Poland" },
      { value: "PT", label: "Portugal" },
      { value: "QA", label: "Qatar" },
      { value: "RO", label: "Romania" },
      { value: "RU", label: "Russia" },
      { value: "RW", label: "Rwanda" },
      { value: "SA", label: "Saudi Arabia" },
      { value: "SN", label: "Senegal" },
      { value: "RS", label: "Serbia" },
      { value: "SG", label: "Singapore" },
      { value: "SK", label: "Slovakia" },
      { value: "SI", label: "Slovenia" },
      { value: "ZA", label: "South Africa" },
      { value: "ES", label: "Spain" },
      { value: "LK", label: "Sri Lanka" },
      { value: "SD", label: "Sudan" },
      { value: "SE", label: "Sweden" },
      { value: "CH", label: "Switzerland" },
      { value: "SY", label: "Syria" },
      { value: "TW", label: "Taiwan" },
      { value: "TZ", label: "Tanzania" },
      { value: "TH", label: "Thailand" },
      { value: "TN", label: "Tunisia" },
      { value: "TR", label: "Turkey" },
      { value: "UG", label: "Uganda" },
      { value: "UA", label: "Ukraine" },
      { value: "AE", label: "United Arab Emirates" },
      { value: "GB", label: "United Kingdom" },
      { value: "US", label: "United States" },
      { value: "UY", label: "Uruguay" },
      { value: "UZ", label: "Uzbekistan" },
      { value: "VE", label: "Venezuela" },
      { value: "VN", label: "Vietnam" },
      { value: "YE", label: "Yemen" },
      { value: "ZM", label: "Zambia" },
      { value: "ZW", label: "Zimbabwe" },
    ],
  },
};

// design: {
//   label: "Design",
//   options: [
//     {
//       label: "Wireframes",
//       value: "wireframes",
//       price: 500,
//     },
//     {
//       label: "Low-Fidelity (Lo-Fi) Design",
//       value: "lofi",
//       price: 1000,
//     },
//     {
//       label: "High-Fidelity (Hi-Fi) Design",
//       value: "hifi",
//       price: 2000,
//     },
//     {
//       label: "Minimal Viable Product (MVP) Design",
//       value: "mvp",
//       price: 1500,
//     },
//     {
//       label: "Not Required",
//       value: "not-required",
//       price: 0,
//     },
//   ],
// },
// development: {
//   label: "Development",
//   options: [
//     {
//       label: "Basic Development",
//       value: "basic-development",
//       price: 2000,
//     },
//     {
//       label: "Standard Development",
//       value: "standard-development",
//       price: 4000,
//     },
//     {
//       label: "Custom Development",
//       value: "custom-development",
//       price: 6000,
//     },
//     {
//       label: "Full Stack Development",
//       value: "full-stack-development",
//       price: 8000,
//     },
//     {
//       label: "MVP Development",
//       value: "mvp-development",
//       price: 3000,
//     },
//     {
//       label: "Ongoing Development/Support",
//       value: "ongoing-development-support",
//       price: 1000,
//     },
//     {
//       label: "Not Required",
//       value: "not-required",
//       price: 0,
//     },
//   ],
// },
// numOfPages: {
//   label: "No. of pages",
//   options: [
//     {
//       label: "1-3",
//       value: "1-5-pages",
//       price: 500,
//     },
//     {
//       label: "3-8",
//       value: "6-10-pages",
//       price: 1000,
//     },
//     {
//       label: "8-12",
//       value: "11-20-pages",
//       price: 1500,
//     },
//     {
//       label: "12-20",
//       value: "21-50-pages",
//       price: 2500,
//     },
//     {
//       label: "20+",
//       value: "50-plus-pages",
//       price: 4000,
//     },
//   ],
// },
// timeline: {
//   label: "Timeline",
//   options: [
//     {
//       label: "1-2 Weeks",
//       value: "1-2-weeks",
//       price: 1000,
//     },
//     {
//       label: "3-4 Weeks",
//       value: "3-4-weeks",
//       price: 500,
//     },
//     {
//       label: "1-2 Months",
//       value: "1-2-months",
//       price: 0,
//     },
//     {
//       label: "3-6 Months",
//       value: "3-6-months",
//       price: -500,
//     },
//     {
//       label: "6+ Months",
//       value: "6-plus-months",
//       price: -1000,
//     },
//   ],
// },
// platformType: {
//   label: "Platform Type",
//   options: [
//     {
//       label: "Web",
//       value: "web",
//       price: 1000,
//     },
//     {
//       label: "Web (Responsive)",
//       value: "web-and-mobile",
//       price: 2000,
//     },
//     {
//       label: "Mobile (iOS/Android)",
//       value: "mobile-ios-android",
//       price: 3000,
//     },
//     {
//       label: "Desktop Application",
//       value: "desktop-application",
//       price: 4000,
//     },
//     {
//       label: "Other Platform",
//       value: "other-platform",
//       price: 2000,
//     },
//   ],
// },
// maintainanceAndSupport: {
//   label: "Maintenance and Support",
//   options: [
//     {
//       label: "No Support",
//       value: "no-support",
//       price: 0,
//     },
//     {
//       label: "Basic Support (Bug Fixes & Minor Updates)",
//       value: "basic-support",
//       price: 500,
//     },
//     {
//       label: "Standard Support (Regular Updates & Bug Fixes)",
//       value: "standard-support",
//       price: 1000,
//     },
//     {
//       label: "Premium Support (Priority Support & Major Updates)",
//       value: "premium-support",
//       price: 1500,
//     },
//     {
//       label: "24/7 Support",
//       value: "24-7-support",
//       price: 2000,
//     },
//   ],
// },
// budget: {
//   label: "Budget",
//   min: 200,
//   max: 10000,
//   step: 100,
// },
